### ISSUE TITLE
Connections are not closed properly in passive mode

### ISSUE THREAD

**Issue by LolHens** [biddster/node-red-contrib-ftp-server#12]
In passive mode the data connections are not properly closed and the ports stay blocked.
This is an issue of the ftpd library and the following PR fixes this behavour: https://github.com/svrooij/nodeftpd/pull/1
Sadly the original project (https://github.com/nodeftpd/nodeftpd) doesn't seem to be active anymore.
Maybe this project could switch to @svrooij/ftpd if the PR gets merged.

**Comment by biddster** [comment]
Looks like it got merged. Let me know when it gets released and I'll take a look. Thanks for your efforts @LolHens.

**Comment by LolHens** [comment]
The library is now released: https://www.npmjs.com/package/@svrooij/ftpd

**Comment by biddster** [comment]
@LolHens, I've updated this now. Fancy doing some testing for me?

**Comment by LolHens** [comment]
I haven't done any load testing yet but just uploading a few files is working fine without any of the previous issues!

**Comment by biddster** [comment]
I haven't released this yet @LolHens . I'm assuming you pulled it from the git branch?

**Comment by LolHens** [comment]
yup. should I leave this issue open for now?

**Comment by biddster** [comment]
Nope, just wanted to make sure you knew I hadn't released it formally and was testing against the right stuff. I very much appreciate you testing it, thank you. I'll release it formally later today.

**Comment by biddster** [comment]
Released at 1.0.0. Thanks for all the help @LolHens.
