### ISSUE TITLE
Tests are broken by recent merges

### ISSUE THREAD

**Issue by biddster** [biddster/node-red-contrib-ftp-server#15]
Recent contributions have broken the test. I didn't spot the issues in the code reviews. The passive port ranges configuration blows up on split string if it's undefined. For backwards compatibility we need to guard against undefined.

**Comment by LolHens** [comment]
#16 should fix the issue

**Comment by biddster** [comment]
I've merged #16 but the test is still failing @LolHens. I'll do some more investigation.

**Comment by LolHens** [comment]
Oh that is strange. Sorry for breaking the tests.

**Comment by biddster** [comment]
No problem. 

I can't release a new version until I understand why though. 

I'll start chopping the code changes until I know what's causing it.

**Comment by biddster** [comment]
Think it's an issue with the test as it was expecting one output and now there's two.

**Comment by biddster** [comment]
Fixed
