### ISSUE TITLE
Support ftp clients which require a path

### ISSUE THREAD

**Issue by biddster** [biddster/node-red-contrib-ftp-server#3]
Some ftp clients (i.e. cameras) only function if they can create a folder structure. We currently don't support that. Need to look at handling mkdir etc so we can create a virtual in memory directory etc that the clients can query.

**Comment by mikebiddell** [comment]
That would be extremely helpful. This node would then support most cameras, if not ALL.

**Comment by biddster** [comment]
Fixed in 0.2.0 which has been released to npm @mikebiddell.
