### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by det-peralta** [biddster/node-red-contrib-ftp-server#6]
I have this problem any suggestion?
![dd](https://user-images.githubusercontent.com/35231379/41944125-42ec6c12-799e-11e8-801e-e5392aefa5e5.PNG)

![fff](https://user-images.githubusercontent.com/35231379/41986004-c9a0a028-7a2c-11e8-9cf1-cdbc4049b8e4.PNG)

**Comment by det-peralta** [comment]
More debug - ftp server 

Doesnt allow upload

![capture2](https://user-images.githubusercontent.com/35231379/41985809-42b19f18-7a2c-11e8-9443-4b1e9b936758.PNG)

Allow Upload

![capture](https://user-images.githubusercontent.com/35231379/41985822-4cb20f48-7a2c-11e8-8f0d-b9b450b041f7.PNG)

**Comment by det-peralta** [comment]
to use passive mode ftp in a docker container image, you need to add "-p 7021:7021 --net=host": 
Example:
`docker run -it -p 1880:1880 -p 7021:7021 --net=host nodered/node-red-docker`

**Comment by biddster** [comment]
Many thanks for the report.

Can you give me some details of your node-red setup? I think you've configured node-red-contrib-ftp-server to listen on port 1881?

I don't understand what the Baby FTP Server screen shots are showing me? How do they relate to this node?

**Comment by det-peralta** [comment]
Thank you very much for the wonderful work. I am using my node-red in a container docker and this way I was not able to use your node, because some cameras have by default the passive ftp mode enabled, without being possible to change it. The only way to make it work was to open port 21 on the container and map it to the internal port, that is, 21: 7021. In case of 1881 was upload error, I sent the wrong screenshot. in the case of BabyFTP is just a program to test your node. One thing I would like to ask is, if you can upgrade the node to v8.0, especially for Home Assistant users, because the version of the HA node only works in this version.
